### PR TITLE
Issue/35

### PR DESCRIPTION
**Pull request by ghost**
My solution proposed for issue #35. As suggested by Frank, I used if statements to conditionally print the singular or plural version of row(s)/column(s)/etc.

### CODE REVIEW

**Comment by FRosner** [comment]
@bkomboz this pull requests also contains the #23 commit for some reason. Also, the code coverage decreased. Please fix this and ping me so I can start reviewing.

**Comment by ghost** [comment]
@FRosner Done, thanks to @Gerrrr for helping me. :+1:

**Comment by ghost** [comment]
@FRosner: Sorry, I accidently removed some of the code yesterday when doing the rebase. The initial solution had tests and also printed the merge rate (which was the purpose of #35). I fixed this, please find the full solution proposal now in branch issue/35.

But the results of the following check confuse me:

```
it should "succeed if a join on the given columns yields at least one row" in {
  val base = makeIntegersDf(List(1, 2, 3), List(1, 2, 5), List(1, 3, 3))
  val ref = makeIntegersDf(List(1, 2, 100), List(1, 5, 100))
  val check = Check(base).isJoinableWith(ref, "column1" -> "column1", "column2" -> "column2")
  val constraint = check.constraints.head
  val result = ConstraintSuccess("Columns column1->column1, column2->column2 can be used for joining (number of distinct rows in base table: 2, number of distinct rows after joining: 1, merge rate: 0.50)")
  check.run().constraintResults shouldBe Map(constraint -> result)
}
```

Why are there two distinct rows in base table? I see three (looking only at the join columns): (1, 1), (2, 2) (3, 5)?

**Comment by FRosner** [comment]
I had some conflicts with #23 and tried to resolve them. Can you please review it? I created a new PR for the rebases branch in https://github.com/FRosner/drunken-data-quality/pull/64.

**Comment by ghost** [comment]
LGTM!

**Pull request closed without merging**
